### PR TITLE
Bugfix/artifacts on s3

### LINKED ISSUE #74: MlflowDataSet fails to log on remote storage when underlying dataset filepath is converted as a PurePosixPath
When I register a dataset in the catalog.yml

```yaml
my_dataset:
  type : kedro_mlflow.io.MlflowDataSet 
  data_set : 
    type: pickle.PickleDataSet
    filepath: data/02_intermediate/my_dataset.pkl
```

and I run `kedro run` I got a `expected string or bytes-like object` when **the local path is linux AND the `mlflow_tracking_uri` is an Azure blob storage (it works locally)**. I don't know really why this append, but it can be fied by replacing `self._filepath` by `self._filepath.as_posix()` in these 2 locations: 

https://github.com/Galileo-Galilei/kedro-mlflow/blob/94bae3df9a054c85dfc0bf13de8db876363de475/kedro_mlflow/io/mlflow_dataset.py#L51

https://github.com/Galileo-Galilei/kedro-mlflow/blob/94bae3df9a054c85dfc0bf13de8db876363de475/kedro_mlflow/io/mlflow_dataset.py#L55

@kaemo @akruszewski did you experience some issues with S3 too?

**EDIT**: @akruszewski it is [the very same issue you encountered here](https://github.com/akruszewski/kedro-mlflow/commit/41e9e3fdd2c54a774cca69e1cb52e26cadf50b1e)

### PR DESCRIPTION
**Pull request by Galileo-Galilei**
This fixes #74. I can't really test if because I would need an access to an azure blob storage while testing, but I tested it locally and it really fixes the bug.

It must be merged after #68 to avoid conflicts.

### CODE REVIEW

**Comment by kaemo** [comment]
@Galileo-Galilei I've tried running MLflow with MinIO recently and it worked fine for me. I'm wondering if we should also do the same thing with `artifact_path`.

**Comment by akruszewski** [comment]
@Galileo-Galilei @kaemo it would be nice (like Kajetan suggested) to make this fix also for `artifact_path`.

**Comment by kaemo** [comment]
> @Galileo-Galilei I've tried running MLflow with MinIO recently and it worked fine for me. I'm wondering if we should also do the same thing with `artifact_path`.

I've just noticed that this is happening for `run_id` cases and I didn't check that one so it might aswell be happening on MinIO/S3.

**Review by kaemo — CHANGES_REQUESTED** [review]
Please add the same thing for `artifact_path`.

**Comment by Galileo-Galilei** [comment]
I don't think this makes sense, because **`artifact_path` is NOT a path** (see the [mlflow documentation](https://www.mlflow.org/docs/latest/_modules/mlflow/tracking/fluent.html#log_artifacts), it is only the name of the remote repository under which the artifact will be logged. It is considered as a run-relative path automatically appended at the end of the "actual" path of the run in the mlflow server.

Have you tried your suggestion ? mlflow complains if you try to convert `artifact_path.as_posix()`.

Did you experience any bug?

**Pull request merged**
