### PR TITLE
Codebase formatting using isort, black and others plus pre-commit

### PR DESCRIPTION
**Pull request by kaemo**
Hi,

Just this week I was about to start my work on an MLflow plugin for Kedro and I found your repository. As I don't want to repeat the work you've already done, I'd like to contribute to your efforts.

First off, I'd like to propose using pre-commit with a certain number of plugins enabled by default. Those are:

- black for code formatting,
- isort for import sorting (with addition of seed-isort-config plugin),
- flake8,
- some other minor but convenient plugins (see `.pre-commit-config.yaml` file).

Those plugins are also used by `kedro lint` and the Kedro project itself so it would make the codebases more familiar to users of kedro.

I skipped the flake8 run for now, because there are a lot of unused import errors which I wanted to ask about. Here they are:

```console
$ pre-commit run --all-files
black....................................................................Passed
seed isort known_third_party.............................................Passed
isort....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

kedro_mlflow/mlflow/__init__.py:1:1: F401 '.kedro_pipeline_model.KedroPipelineModel' imported but unused
kedro_mlflow/cli/cli.py:7:1: F401 'kedro.cli.get_project_context' imported but unused
kedro_mlflow/cli/cli.py:8:1: F401 'kedro.context.load_context' imported but unused
kedro_mlflow/io/__init__.py:1:1: F401 '.mlflow_dataset.MlflowDataSet' imported but unused
kedro_mlflow/hooks/__init__.py:1:1: F401 '.node_hook.MlflowNodeHook' imported but unused
kedro_mlflow/hooks/__init__.py:2:1: F401 '.pipeline_hook.MlflowPipelineHook' imported but unused
kedro_mlflow/io/mlflow_dataset.py:1:1: F401 'copy.deepcopy' imported but unused
kedro_mlflow/io/mlflow_dataset.py:2:1: F401 'pathlib.PurePath' imported but unused
kedro_mlflow/hooks/node_hook.py:1:1: F401 're' imported but unused
kedro_mlflow/hooks/node_hook.py:7:1: F401 'kedro.pipeline.Pipeline' imported but unused
kedro_mlflow/mlflow/kedro_pipeline_model.py:2:1: F401 'typing.Any' imported but unused
kedro_mlflow/mlflow/kedro_pipeline_model.py:2:1: F401 'typing.Callable' imported but unused
kedro_mlflow/mlflow/kedro_pipeline_model.py:2:1: F401 'typing.Dict' imported but unused
kedro_mlflow/mlflow/kedro_pipeline_model.py:2:1: F401 'typing.Union' imported but unused
kedro_mlflow/mlflow/kedro_pipeline_model.py:5:1: F401 'kedro.pipeline.Pipeline' imported but unused
tests/io/test_mlflow_dataset.py:1:1: F401 'glob' imported but unused
kedro_mlflow/pipeline/__init__.py:1:1: F401 '.modular_pipeline_ml.pipeline_ml' imported but unused
kedro_mlflow/pipeline/__init__.py:2:1: F401 '.pipeline_ml.PipelineML' imported but unused
kedro_mlflow/pipeline/modular_pipeline_ml.py:1:1: F401 'sys' imported but unused
kedro_mlflow/pipeline/modular_pipeline_ml.py:5:1: F401 'yaml' imported but unused
kedro_mlflow/utils.py:1:1: F401 'os' imported but unused
kedro_mlflow/utils.py:5:1: F401 'urllib.parse.urlparse' imported but unused
kedro_mlflow/hooks/pipeline_hook.py:1:1: F401 're' imported but unused
kedro_mlflow/hooks/pipeline_hook.py:11:1: F401 'kedro.pipeline.node.Node' imported but unused
kedro_mlflow/hooks/pipeline_hook.py:17:1: F401 'kedro_mlflow.utils._get_package_requirements' imported but unused
kedro_mlflow/hooks/pipeline_hook.py:17:1: F401 'kedro_mlflow.utils._get_project_globals' imported but unused
kedro_mlflow/pipeline/pipeline_ml.py:1:1: F401 'pathlib.Path' imported but unused
kedro_mlflow/pipeline/pipeline_ml.py:2:1: F401 'typing.Any' imported but unused
kedro_mlflow/pipeline/pipeline_ml.py:2:1: F401 'typing.Dict' imported but unused
kedro_mlflow/context/__init__.py:4:1: F401 '.mlflow_context.KedroMlflowContext' imported but unused
kedro_mlflow/context/__init__.py:4:1: F401 '.mlflow_context.get_mlflow_conf' imported but unused

Check for merge conflicts................................................Passed
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
```

Are those unused imports needed for something or can I safely remove them?

### CODE REVIEW

**Comment by Galileo-Galilei** [comment]
Hello, 
First of all, many thanks for your interest and your will to participate to this project. I'd be glad to discuss with you about the features provided by the package (do they meet most of your use-cases? are there easy to use ?).

Regarding the pull requests, here are some comments / questions about your differents commits : 
-Definitely ok for pre-commit, this is a best practice
- I am aware that the linting is quite poor at the moment, and I planned to fix it within few weeks but you reacted faster ;) On a day to day basis I use to lint with pylint and i changed the ``kedro lint`` command accordingly. Is there **any deep reason you want to use black over pylint?** (I understand that you want to stick with kedro convention though). 
- I saw that ``kedro`` does not support python 3.8 (it make the CI fails...) but **why did you remove python 3.5** too?
- regarding the backlash bugfix, I'd rather **stick to ``pathlib`` for joining the strings** (rather than ``os.path.join``) to be consistent with ``kedro`` but this is a minor detail
- Many **unused imports can be removed**, I'll add some extra cleaning ASAP and this is directly related to linting. The **only imports that should be kept are the ones in the ``__init__.py`` files** because they are used for importing at the top level of each module and removing them may break other scripts.
- Regarding the requirements, I **deliberately did not install directly from kedro's develop branch**. My concerns here are the following : 
    - you must be aware that you are on the development branch because **it impacts your project template** (especially because of hooks), but I don't want to mess up with your current kedro version  and I wanted to force the user to do the install manually and not to "hide" it (it may have side effects on your current project, and it is quite "invisible" that you use the develop branch because the displayed version is still 0.15.9)
    - the **develop branch may not be stable** (although kedro maintainers try to enforce stability) : it would be  better to specifiy a given commit rather thant the last modification of the develop branch
    - ``kedro-mlflow`` does not need to install pandas dependencies, it is only for the example to run. If you use kedro's develop branch, **you very likely have to install the dependencies manually** (not only pandas). It **may be confusing since current stable releases do not use this feature** so I'd rather make this installation explicit.
- **Linting should avoid the ``template`` folder**, it currently breaks the CI.

I am very busy this week but **I will definitely merge your PR by next week**!

**Comment by kaemo** [comment]
Hi @Galileo-Galilei,

Thanks for the reply. I'll start with giving you a little bit of context for my involvement here. I'm one of the core architects and developers behind ML Ops framework in the company I'm working for (big pharma). Initially we created our own framework but about two months ago we found out about Kedro which, to our surprise, is almost 90% identical in terms of design decisions to what we have created. Because Kedro is more mature than our framework we decided to go with it and I'm now working on MLflow integration. In our framework we mostly used it to automatically track parameters, metrics, tags models and artifacts (through a function decorator). This is what I mostly care about at this point in terms of functionality. On our roadmap is also automatic way of containerising the models (we're thinking ONNX+TF Serving or ONNX+MLflow; I'm also creating a kedro-onnx plugin to have a common model format). For versioning we want to evaluate Kedro+S3, Kedro+DVC and Kedro+MLflow - we haven't decided yet.

I haven't been able to test the plugin yet, because it wasn't working. I'll be testing it this week and I'll come back with my thoughts.

Now, responding to your questions about my PR and some decisions in it:

- We use black internally for all DS/ML projects as a part of standardisation efforts; it's also used by kedro. For the plugin I would stick with black as it'll make it more familiar for other people within kedro ecosystem if we stick to one code style convention.
- I removed Python 3.5 because Kedro is also not supporting it. See https://github.com/quantumblacklabs/kedro/blob/develop/setup.py
- I'll change the use of `os.path.join` to `pathlib` today, not a problem!
- I can clean the unused imports within this PR. I'll leave the imports in `__init__.py` files and add flake8's `noqa` statements where needed.
- I can remove the `kedro[pandas]` dependency, but if it makes any functionality unavailable, I think it should be included by default (I haven't tested everything yet so I don't know about that).
- I can revert the changes regarding the develop version in the requirements but:
    - This will cause GitHub workflow to fail - it installs the PYPI version which doesn't have the required functionalities. The solution could be to have a separate requirements file for the GitHub Workflows to make it work, but that would create two separate requirements files and I'm not a fan of such solution.
    - speaking more generally, this plugin is not mature enough to be used/released on PYPI as of today (it's using unreleased functionality and still has some bugs), so I would leave the usage of develop branch on GitHub for now until the required functionality in Kedro is released. This makes it installable using one pip command/requirements entry and will work for GitHub Workflows. Personally, I'd inform potential users about plugin's development status and dependency on develop branch of Kedro in `README.md` (one needs to read it anyway to install the plugin, because it's not on PYPI yet). In future, when kedro with required functionalities is released, that could be changed back to the PYPI version of Kedro and `kedro-mlflow` could be released on PYPI at that point. Let me know if that sounds reasonable.
- The `run.py` file in template is already excluded from the pre-commit hooks. Will that suffice?

Future considerations:

- What do you think about incorporating poetry into the project? It would allow us to share the locked dependencies for package versions and development tooling and to release PYPI package very easily in the future. We use it internally for Python packages development and it works like a charm.
- I plan to work on this integration regularly in the foreseeable future. It would be great to discuss how can we work together on it, the vision and roadmap etc. What do you think? What would be the best way to go about it?

**Comment by kaemo** [comment]
I just found out that there is a [`pre-commit` action](https://github.com/pre-commit/action). I think it would be a good idea to switch from flake8 in `.github/workflows/pythonpackage.yml` to running pre-commit action - the proposed pre-commit config in `.pre-commit-config.yml` has already flake8 (and more). It would be advantageous to have a single source of truth for code checks. It would also protect the repository from PRs with code that was pushed without running pre-commit checks and fixes.

**Comment by Galileo-Galilei** [comment]
Hello, 

I've merged the PR, thanks for your job!

Some answers regarding the PR:
- let's go with black!
- ok for python 3.5
- thanks for pathlib
- thanks for #noqa in the ```__init__.py``` files
- I removed ```kedro[pandas]``` from the ```requirements.txt``` file. It is not required at all for the package. I emphasized on it in the example because it is very likely that you use ```pandas``` in your data science project and it may be confusing if you switch from the standard kedro to the ```develop``` version (because current version of kedro do not need this extra import).
- I agree, by now it is more important to keep the github workflow stable. Ok to wait for the kedro official release and insist on it the ```README.md```
- It is likely that we should exclude more files in the template in the future, but I think excluding only the ```run.py``` is sufficient for now.

Regarding your questions:
- I am not familiar with```poetry```, but I am not really opinionated in package development so **we can go with it you want**.
- I am **glad you want to get deeply involved and I strongly thank you for this**! I am not really familiar with open source development and I don't know what is the best way to collaborate. I suggest the following:
    1. I've just opened **2 projects**. One for ongoing development for the feature we prioritize, and one more high level for the roadmap. I suggest that we **open one issue for each feature** to keep track of the discussion and organize ourselves. **Feel free to suggest another way to proceed** if you do not find it satisfying.
    2. I can **give you maintainer access** to manage the repo if it is easier for you to integrate your developments.
    3. Regarding the roadmap, **my top level priorities** at the moment are:
        1. **adding unit tests**: we cannot seriously collaborate if the project is instable and we cannot synchronize our work with high confidence and prevent regression. I plan to do this in the coming weeks.
        2. **Add proper documentation**: The ```README.md``` is not well written and needs serious refactoring and more detailed explanations. The more detailed the description, the easier it is to discuss the desirable functionnalities.
- I don't personnaly feel that it is necessary at this point, but if you find it mandatory for proper collaboration we can enforce it. By now I feel that we can develop faster without this constraint, and having tests will prevent the master to break which is my sole constraint right now. If the project gets bigger, wecan switch to a more formal git development flow.

**Comment by kaemo** [comment]
@Galileo-Galilei maintainer status would definitely make my life easier. Forking workflow is not very convenient in a long run. Let's keep the workflow simple for now - master branch plus bug/feature branches.

I agree with the priorities you have outlined. Apart from that, my main priority for now is to do manual tests of the functionalities currently available (I wasn't able to do that last week because of some other commitments) and post bugs and clarification/feature requests as issues.

I'll move further discussions into separate issues from this point forward.

**Comment by Galileo-Galilei** [comment]
I temporarily reopen this issue, because we updated recently the pre-commit but not the test_requirements.txt for new black, isort and flake8 version and this creates conflicts.

**Pull request merged**
