### PR TITLE
Implement missing PipelineML slicing functionalities

### PR DESCRIPTION
**Pull request by Calychas**
## Description
Implements the rest of PipelineML slicing functionalities. 

## Development notes
Currently, when something fails while running a pipeline, kedro tries to provide a hint command to resume. However, as PipelineML doesn't implement them all, it throws an additional error while trying to provide a hint. This results in messy logging on the actual error (you need to scroll up to see what actually broke), and oftentimes one can mistakenly think that something went wrong during packaging of the model.

This PR tries to fix this problem.

## Checklist

- [x] Read the [contributing](https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/CONTRIBUTING.md) guidelines
- [x] Open this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Update the documentation to reflect the code changes
- [ ] Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- [ ] Add tests to cover your changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by Galileo-Galilei** [comment]
Definitely fine with that, this would be a partial solution to #377.

**Comment by Calychas** [comment]
Hey! Yes, I will fix the failing tests and add some more

**Comment by Galileo-Galilei** [comment]
I took the liberty to go ahead and fix the tests, hope you don't mind. Thank you very much for the contribution!

**Comment by kacper-ki** [comment]
Not at all @Galileo-Galilei. Thanks!

**Pull request merged**
