### PR TITLE
FIX  #14 - Remove unintended warning message when calling 'kedro mlfow init' command

### LINKED ISSUE #14: Warning message appears when calling ``kedro mlflow init``
The warning claims that the project is not initialised yet, and that you must call ``kedro mlflow init`` before calling any command while you are calling ``kedro mlflow init``. It can be safely ignored because the command works as intended. This bug is due to the dynamic creation of command.

### PR DESCRIPTION
**Pull request by Galileo-Galilei**
Fix this bug which is annoying with a false warning (even if the function call was ok)

### CODE REVIEW

**Review by akruszewski — APPROVED** [review]

**Comment by akruszewski** [comment]
@Galileo-Galilei looks good :+1:.

**Comment by Galileo-Galilei** [comment]
@kaemo are you ok with it? If you don't have time, I'll consider @akruszewski review as sufficient for merging.

**Comment by kaemo** [comment]
@Galileo-Galilei Sorry I wasn't available - I had to do uni projects, but I'm back now :)

**Comment by Galileo-Galilei** [comment]
No problem we're all busy + this is a minor PR with no design decisions involved, this is less important to be all aligned in this situation. One review is enough!

**Pull request merged**
