### PR TITLE
Versioned datasets handled correctly by MLflowDataSet

### PR DESCRIPTION
**Pull request by akruszewski**

### CODE REVIEW

**Comment by Galileo-Galilei** [comment]
Well spotted! Can you  : 
  - Add  a test to ensure test coverage is still 100%
  - Update the CHANGELOG.MD file to reflect your change 
  - Squash all commits into one
  -

**Comment by kaemo** [comment]
@Galileo-Galilei I can merge this after making sure that all is done according to our contribution guidelines if you don't mind.

**Comment by kaemo** [comment]
@akruszewski Please have a look at [contribution guidelines](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CONTRIBUTING.md).

**Comment by akruszewski** [comment]
@Galileo-Galilei Thanks! To be fair it was spotted by @kaemo :).

All requested changes applied.

@kaemo please review.

**Pull request merged**
