### PR TITLE
Python 311 Test

### PR DESCRIPTION
**Pull request by rxm7706**
Add Python311 to setup
Test Matrix for 3.8 to 3.11
Publish and Pre-release - 3.9 changed to 3.11

## Description
Why was this PR created?
Close https://github.com/Galileo-Galilei/kedro-mlflow/issues/449

## Development notes
What have you changed, and how has this been tested?

## Checklist

- [x] Read the [contributing](https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/CONTRIBUTING.md) guidelines
- [x] Open this PR as a 'Draft Pull Request' if it is work-in-progress
- [] Update the documentation to reflect the code changes
- [] Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- [x] Add tests to cover your changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by Galileo-Galilei** [comment]
Thanks for this! I am pretty sure the tests are failing for things unrelated to python 3.11 but rather to most recent kedro versions. I need to check in details, maybe this weekend.

**Comment by Galileo-Galilei** [comment]
Hi @rxm7706, sorry for the very late reply. It's almost good to go for me (the failing tests do not come from your PR). Can you just add an entry in the changelog? I'll merge it immediately after.

**Comment by Galileo-Galilei** [comment]
Hi @rxm7706, if it's ok for you, I'll take over it!

**Comment by rxm7706** [comment]
@Galileo-Galilei please do !

**Pull request merged**
