### PR TITLE
FIX #116 - Pass filepath in MlflowAbstractModelDataSet through PurePosixPath in init

### LINKED ISSUE #116: TypeError: unsupported operand type(s) for /: 'str' and 'str' when using MlflowArtifactDataSet with MlflowModelSaverDataSet
## Description

`TypeError: unsupported operand type(s) for /: 'str' and 'str'` occurs when `MlflowArtifactDataSet` is used with `MlflowModelSaverDataSet`.

## Context

Logging locally and to MLflow in one step.

## Steps to Reproduce

```yaml
sklearn_model:
    type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
    data_set:
        type: kedro_mlflow.io.models.MlflowModelSaverDataSet
        flavor: mlflow.sklearn
        filepath: data/06_models/sklearn_model
        versioned: true
```

## Expected Result

The model should be saved locally and in MLflow run at the same time.

## Actual Result

```
Traceback (most recent call last):
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/io/core.py", line 240, in save
    self._save(data)
  File "/Users/olszewk2/dev/pyzypad-example/src/kedro-mlflow/kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py", line 40, in _save
    if hasattr(self, "_version")
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/io/core.py", line 605, in _get_save_path
    versioned_path = self._get_versioned_path(save_version)  # type: ignore
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/io/core.py", line 616, in _get_versioned_path
    return self._filepath / version / self._filepath.name
TypeError: unsupported operand type(s) for /: 'str' and 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 725, in main
    cli_collection()
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/olszewk2/dev/pyzypad-example/kedro_cli.py", line 230, in run
    pipeline_name=pipeline,
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 767, in run
    raise exc
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 759, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/runner/runner.py", line 101, in run
    self._run(pipeline, catalog, run_id)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/runner/sequential_runner.py", line 90, in _run
    run_node(node, catalog, self._is_async, run_id)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/runner/runner.py", line 213, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/runner/runner.py", line 249, in _run_node_sequential
    catalog.save(name, data)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/io/data_catalog.py", line 448, in save
    func(data)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/io/core.py", line 625, in save
    super().save(data)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/io/core.py", line 247, in save
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while saving data to data set MlflowMlflowModelSaverDataSet(filepath=/Users/olszewk2/dev/pyzypad-example/data/06_models/pclass_encoder, flavor=mlflow.sklearn, load_args={}, save_args={}, version=Version(load=None, save='2020-11-06T12.28.57.593Z')).
unsupported operand type(s) for /: 'str' and 'str'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* kedro 0.16.6
* kedro-mlflow 0.4.0
* Python 3.7.7
* MacOS Catalina

## Does the bug also happen with the last version on develop?

Yes.

### PR DESCRIPTION
**Pull request by kaemo**
## Description

Closes #116.

## Development notes
What have you changed, and how has this been tested?

## Checklist

- [x] Read the [contributing](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CONTRIBUTING.md) guidelines
- [x] Open this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Update the documentation to reflect the code changes
- [x] Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- [x] Add tests to cover your changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by kaemo** [comment]
@Galileo-Galilei Hey Yolan, sorry for such a long radio silence - I'm ultra busy with a new project at work and the new semester began at uni. Amazing job with taking such great care of the project. Kudos!

**Comment by Galileo-Galilei** [comment]
Hello Kajetan, no worry we're all busy and have our own projects and life side this project. Taki Eddine and I were very committed to make the project work with `kedro>=0.16.5` to enhance adoption so we work hard for that.

Regarding your PR, it's not the first time that I made this mistake nor the first time you offer a solution that does not work on Windows, I think we had the exact same PR about `MlflowArtifactDataSet` :)

To pass windows tests, can you add:

```python

from kedro.io.core import get_protocol_and_path
<...>
_, path = get_protocol_and_path(filepath, version)
super().__init__(PurePosixPath(path), version)

```
and reinject this kedro-formatted path to the underlying dataset?

You can fin an example in the [pandas.CSVDataSet](https://github.com/quantumblacklabs/kedro/blob/master/kedro/extras/datasets/pandas/csv_dataset.py) and see why this is necessary in [io.core](https://github.com/quantumblacklabs/kedro/blob/master/kedro/io/core.py). They do a special treatment on windows path, and deal with the `file:///` protocol for local files.

On the way, can you update the documentation for model and add a subsection in the FAQ : https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/docs/source/03_tutorial/06_version_models.md#how-can-i-track-a-custom-mlflow-model-flavor
(Feel free to modify below formulation)

```mardown
## How to log both locally and remotely
 If you want to save your model both locally and remotely within the same dataset saving, you can leverage `MlflowArtifactDataSet` 

<code>yaml
sklearn_model:
    type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
    data_set:
        type: kedro_mlflow.io.models.MlflowModelSaverDataSet
        flavor: mlflow.sklearn
        filepath: data/06_models/sklearn_model
        versioned: true
</code>

Note that in current version (kedro-mlflow=0.4.0) this is equivalent to logging the model remotely with `MlflowModelLoggerDataSet`, but in the future some additional model-specific features may be added to `MlflowModelLoggerDataSet` (for integration with Mlflow Model Registry for instance), and the 2 call may become different.
```

**Review by Galileo-Galilei — CHANGES_REQUESTED** [review]
Hello Kajetan, no worry we all have our own projects and life aside this project. Taki Eddine and I were very committed to make the project work with `kedro>=0.16.5` to enhance adoption so we work hard for that in the past weeks but there is no problem you were busy elsewhere.

Regarding your PR, it's not the first time that I made this mistake nor the first time you offer a solution that does not work on Windows, I think we had the exact same PR about `MlflowArtifactDataSet` :)

To pass windows tests, can you add:

```python

from kedro.io.core import get_protocol_and_path
<...>
_, path = get_protocol_and_path(filepath, version)
super().__init__(PurePosixPath(path), version)

```
and reinject this kedro-formatted path to the underlying dataset?

You can fin an example in the [pandas.CSVDataSet](https://github.com/quantumblacklabs/kedro/blob/master/kedro/extras/datasets/pandas/csv_dataset.py) and see why this is necessary in [io.core](https://github.com/quantumblacklabs/kedro/blob/master/kedro/io/core.py). They do a special treatment on windows path, and deal with the `file:///` protocol for local files.

On the way, can you update the documentation for model and add a subsection in the FAQ : https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/docs/source/03_tutorial/06_version_models.md#how-can-i-track-a-custom-mlflow-model-flavor
(Feel free to modify below formulation)

```mardown
## How to log both locally and remotely
 If you want to save your model both locally and remotely within the same dataset saving, you can leverage `MlflowArtifactDataSet` 

<code>yaml
sklearn_model:
    type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
    data_set:
        type: kedro_mlflow.io.models.MlflowModelSaverDataSet
        flavor: mlflow.sklearn
        filepath: data/06_models/sklearn_model
        versioned: true
</code>

Note that in current version (kedro-mlflow=0.4.0) this is equivalent to logging the model remotely with `MlflowModelLoggerDataSet`, but in the future some additional model-specific features may be added to `MlflowModelLoggerDataSet` (for integration with Mlflow Model Registry for instance), and the 2 call may become different.
```

**Comment by kaemo** [comment]
@Galileo-Galilei thanks for pointing to the Windows issue. I'll update both the code and the documentation.

**Comment by Galileo-Galilei** [comment]
Hi @kaemo, thanks for the job! It seems you're a bit struggling with the windows part (I assume you don't have the possibility to test locally). I have converted the `PurePosixPath` call to `Path` to be os-independen. I've check, it is what we did for `MlflowArtifactDataSet` even if it is slightly different of kedro approach. 

Tell me if it is good to you, I'll squash all commits and merge it then.

**Comment by kaemo** [comment]
@Galileo-Galilei haha you've guessed it! I was really struggling to get this to work on Windows. Looks good to me, you can squash and merge.

**Pull request merged**
