### PR TITLE
Update 01_example_project.md

### PR DESCRIPTION
**Pull request by lawwu**

### CODE REVIEW

**Comment by kaemo** [comment]
@lawwu please branch off the `develop` branch and create a PR to merge the changes into `develop`.

**Comment by kaemo** [comment]
@lawwu Also, if you could make all those typo, grammar and wording fixes on one branch that would be lovely. And thanks for contributing!

**Comment by kaemo** [comment]
@lawwu Make sure to check out our [contributing guide](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CONTRIBUTING.md).

**Comment by Galileo-Galilei** [comment]
I close this since PR #55 includes this one and follow guidelines. Thanks for contributing!

**Pull request closed without merging**
