### PR TITLE
Documentation refactoring

### LINKED ISSUE #16: Understanding PipelineML and pipeline_ml
Hi @Galileo-Galilei. As I mentioned in other issue, I'm working currently with integrating my training and inference pipelines with MLPipeline. Unfortunately I'm confused with handling inputs and outputs, I can't wrap my head around it.

## Context ##

My training pipeline is built from three other pipelines: `de_pipeline` (data engineering), `fe_pipeline` (feature engineering) and `md_pipeline` (training aka. modeling).

My inference pipeline is buit from the same pipelines but with predict argument which change their behavior (they're using previously saved models for imputer and prediction.

In my current implementation it looks like this:  

```python
     de_pipeline_predict = pipeline(
         de.create_pipeline(predict=True),  # type: ignore
         inputs={"remote_raw": "remote_new", "imputer": "imputer"},
         namespace="new",
     )
     fe_pipeline_predict = pipeline(
         fe.create_pipeline(predict=True),  # type: ignore
         namespace="new",
     )

     # `new_preds` output would be mapped to `new.new_preds` because of
     # namespace usage, so we use map `new_preds` to `new_preds` to retain the
     # name and keep catalog clean.
     md_pipeline_predict = pipeline(
         md.create_pipeline(predict=True),  # type: ignore
         inputs={"lgbm": "lgbm"},
         outputs={"new_preds": "new_preds"},
         namespace="new",
```

My pipelines also getting as input parameters, obtained from kedro configuration (by that I mean `conf/base/parameters.yaml`).

When I'm trying to glue them together with:

```python
     train_pipeline = de_pipeline + fe_pipeline + md_pipeline
     predict_pipeline = de_pipeline_predict + fe_pipeline_predict + md_pipeline_predict

     training = pipeline_ml(
         training=train_pipeline,
         inference=predict_pipeline,
     )
```

and running my training pipeline I'm getting:

```
kedro_mlflow.pipeline.pipeline_ml.KedroMlflowPipelineMLInputsError:
        The following inputs are free for the inference pipeline:
        - lgbm
     - remote_new
     - imputer
     - params:data_engineering
     - params:target.
        Only one free input is allowed.
        Please make sure that 'inference' pipeline inputs are 'training' pipeline outputs,
        except one.
```

I'm understand the issue here, but I don't know how to proceed with that ("un-free" inputs which should be obtained (automatically?) using Kedro features). I would be glad for any tips.

### PR DESCRIPTION
**Pull request by Galileo-Galilei**
## Description

This is a huge documentation refactoring. in particular it fixes #16 with documentation and examples for `pipeline_ml_factory`. 

## Development notes

- reorganize documentatio architecture
- proofread the docs, add explanations and fix many typos
- add explanation to for `pipeline_ml_factory`, and using `kedro-mlflow` as a framework in general.

## Checklist

- [X] Read the [contributing](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CONTRIBUTING.md) guidelines
- [X] Open this PR as a 'Draft Pull Request' if it is work-in-progress
- [X Update the documentation to reflect the code changes
- [X] Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- [N/A Add tests to cover your changes

## Notice

- [X] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by Galileo-Galilei** [comment]
@kaemo , @takikadiri  If anyone wants to see what I am doing, it is much more readble if you click the readthdocs links in the tests. I try to document how we can use kedro-mlflow as a ml framework. This is strongly related to https://github.com/quantumblacklabs/kedro/issues/464, but the PR is very incomplete right now. I will provide a code example in a separated repo too.

**Comment by kaemo** [comment]
@Galileo-Galilei I'll have a look at it tomorrow.

**Comment by Galileo-Galilei** [comment]
This is really a draft for now, and far from being finished. I thought I would be able to continue it faster but I do not have a lot of time right now. I am creating an example repo in parallel (private for now) which will demonstrate how to apply the principles described here, and how pipeline_ml_factory might be useful for packaging ml model.

It is not necessary to spend too much time on it, it will likely evolve a lot in coming weeks.

**Comment by Galileo-Galilei** [comment]
Hello @kaemo, @takikadiri, I think we are good to go. Feel free to review when you can :) I'll ship it in the 0.5.0, likely within 3-4 weeks.

For the record, I have created a tutorial with code which may be easier to read that the documentation which is very verbose, see https://github.com/Galileo-Galilei/kedro-mlflow-tutorial.

**Pull request merged**
